name: ci

on:
  push:
    branches:
      - master
      - dev
    tags:
      - '*'     
  pull_request:
    branches:
      - master
      - dev
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
      - unlocked
      - review_requested
  workflow_dispatch:
    
env:
  DOCKER_REGISTRY_REPOSITORY: sysflowtelemetry/sf-policymanager 

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'      
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip          
          python -m pip install black unimport safety bandit        
      - name: Check style
        run: black --check -S -l 120 src/
      - name: Check imports
        run: unimport --check --exclude __init__.py src/
      - name: Check package vulnerabilities
        run: safety check -r src/requirements.txt
      - name: Check code vulnerabilities
        run: bandit -r src/
  docker:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:          
          images: |
            ${{ env.DOCKER_REGISTRY_REPOSITORY }}
            ghcr.io/${{ github.repository }}
          tags: |            
            type=edge,branch=master
            type=ref,event=branch
            type=ref,event=tag            
            type=ref,event=pr
          labels: |
            org.opencontainers.image.documentation=https://sysflow.readthedocs.io/
            org.opencontainers.image.vendor=SysFlow
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        if: ${{ github.event_name != 'pull_request' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}   
      - name: Set build args
        id: args
        shell: bash
        run: |
          echo "##[set-output name=ubi_version;]$(awk -F'=' '/UBI_VERSION/{print $2}' makefile.manifest.inc)"
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/*/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"     
      - name: Build and push
        id: docker_build        
        uses: docker/build-push-action@v2        
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
          build-args: |            
            VERSION=${{ steps.args.outputs.branch }}
            RELEASE=${{ steps.args.outputs.sha_short }}
            UBI_VER=${{ steps.args.outputs.ubi_version }}
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        if: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          destination_container_repo: ${{ env.DOCKER_REGISTRY_REPOSITORY }}
          provider: dockerhub          
          readme_file: "README.md"      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
